In [5]:
import numpy as np



🌟 Exercise 1 : Array Creation and Manipulation
Instructions
Create a 1D NumPy array containing numbers from 0 to 9.

In [8]:
array = np.arange(10)
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

🌟 Exercise 2 : Type Conversion and Array Operations
Instructions
Convert a list [3.14, 2.17, 0, 1, 2] into a NumPy array and convert its data type to integ

In [9]:
ar_list = [3.14, 2.17, 0, 1, 2]
ar_list = np.array(ar_list)
ar_list = ar_list.astype(int)
ar_list

array([3, 2, 0, 1, 2])

🌟 Exercise 3 : Working with Multi-Dimensional Arrays
Instructions
Create a 3x3 NumPy array with values ranging from 1 to 9.

In [10]:
array = np.arange(1, 10).reshape(3, 3)
array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

🌟 Exercise 4 : Creating Multi-Dimensional Array with Random Numbers
Instructions
Create a 2D NumPy array of shape (4, 5) filled with random numbers.



In [17]:
array = np.random.rand(4, 5)
array

array([[0.30110717, 0.55397987, 0.20093998, 0.49003789, 0.23731497],
       [0.51154194, 0.48448488, 0.54517222, 0.51257951, 0.40425047],
       [0.69366188, 0.39451691, 0.64460493, 0.52790839, 0.88376911],
       [0.49999889, 0.09943632, 0.42042327, 0.74365074, 0.41586942]])

🌟 Exercise 5 : Indexing Arrays
Instructions
Select the second row from a given 2D NumPy array.

In [19]:
array[1:2]

array([[0.51154194, 0.48448488, 0.54517222, 0.51257951, 0.40425047]])

🌟 Exercise 6 : Reversing elements
Instructions
Reverse the order of elements in a given 1D NumPy array (first element becomes last).

In [22]:
array = np.arange(10)
array = array[::-1]
array

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

🌟 Exercise 7 : Identity Matrix
Instructions
Create a 4x4 identity matrix using NumPy

In [23]:
identity_matrix = np.eye(4)
identity_matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

🌟 Exercise 8 : Simple Aggregate Funcs
Instructions
Find the sum and average of a given 1D array.

In [27]:
array = np.arange(10)
print(f"Sum: {array.sum()}")
print(f"Mean: {array.mean()}")

Sum: 45
Mean: 4.5


🌟 Exercise 9 : Create Array and Change its Structure
Instructions
Create a NumPy array with elements from 1 to 20; then reshape it into a 4x5 matrix.

In [29]:
array = np.arange(1,21).reshape(4,5)
array


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

🌟 Exercise 10 : Conditional Selection of Values
Instructions
Extract all odd numbers from a given NumPy array.

In [30]:
array = np.arange(10)
array = array[array % 2 == 1]
array

array([1, 3, 5, 7, 9])